#!/bin/bash
# Quick Setup Commands for citricloud.com
# Run these after DNS points to your server (57.129.74.173)

echo "=========================================="
echo "CITRICLOUD.COM - Quick Setup Commands"
echo "=========================================="
echo ""

echo "1. CHECK DNS (should return 57.129.74.173):"
echo "   dig +short citricloud.com"
echo ""

echo "2. INSTALL SSL CERTIFICATE:"
echo "   sudo apt update"
echo "   sudo apt install certbot python3-certbot-nginx -y"
echo "   sudo certbot --nginx -d citricloud.com -d www.citricloud.com"
echo ""

echo "3. TEST WEBSITE:"
echo "   curl -I https://citricloud.com"
echo ""

echo "4. CHECK BACKEND STATUS:"
echo "   ps aux | grep uvicorn | grep -v grep"
echo ""

echo "5. CHECK NGINX STATUS:"
echo "   sudo systemctl status nginx"
echo ""

echo "6. RESTART SERVICES:"
echo "   sudo systemctl restart nginx"
echo "   # Backend restart (if using systemd service):"
echo "   sudo systemctl restart citricloud-backend"
echo ""

echo "7. VIEW LOGS:"
echo "   # Nginx access log"
echo "   sudo tail -f /var/log/nginx/access.log"
echo ""
echo "   # Nginx error log"
echo "   sudo tail -f /var/log/nginx/error.log"
echo ""
echo "   # Backend log"
echo "   cd /home/ubuntu/infrastructure/cloud/web-development/websites/citricloud.com/backend"
echo "   tail -f logs/app.log"
echo ""

echo "8. REBUILD FRONTEND (if needed):"
echo "   cd /home/ubuntu/infrastructure/cloud/web-development/websites/citricloud.com/frontend"
echo "   npm run build"
echo "   sudo systemctl reload nginx"
echo ""

echo "=========================================="
echo "RESEND DNS RECORDS (Add to your DNS)"
echo "=========================================="
echo ""
echo "SPF Record:"
echo "  Type: TXT"
echo "  Name: @"
echo "  Value: v=spf1 include:amazonses.com ~all"
echo ""
echo "DKIM Record (get exact value from Resend):"
echo "  Type: TXT"
echo "  Name: resend._domainkey"
echo "  Value: [provided by Resend]"
echo ""
echo "DMARC Record:"
echo "  Type: TXT"
echo "  Name: _dmarc"
echo "  Value: v=DMARC1; p=none; rua=mailto:dmarc@citricloud.com"
echo ""
echo "MX Record:"
echo "  Type: MX"
echo "  Name: @"
echo "  Value: feedback-smtp.us-east-1.amazonses.com"
echo "  Priority: 10"
echo ""

echo "=========================================="
echo "CLOUDFLARE CONFIGURATION (if using)"
echo "=========================================="
echo ""
echo "1. Go to Cloudflare DNS settings"
echo "2. Update A records:"
echo "   - Name: @ → Value: 57.129.74.173 (Proxy OFF)"
echo "   - Name: www → Value: 57.129.74.173 (Proxy OFF)"
echo "3. Add email DNS records (SPF, DKIM, DMARC, MX)"
echo "4. Wait 5-10 minutes for propagation"
echo "5. Test: dig +short citricloud.com"
echo "6. Once working, you can enable Cloudflare proxy (orange cloud)"
echo ""

echo "=========================================="
echo "Quick Status Check:"
echo "=========================================="
dig +short citricloud.com | head -2
ps aux | grep uvicorn | grep -v grep | wc -l | xargs -I {} echo "Backend running: {}"
sudo systemctl is-active nginx | xargs -I {} echo "Nginx status: {}"
ls -lh /home/ubuntu/infrastructure/cloud/web-development/websites/citricloud.com/frontend/dist/index.html 2>/dev/null | awk '{print "Frontend built: " $9}' || echo "Frontend: Not built"
echo ""

echo "=========================================="
echo "For detailed guide, see:"
echo "  - DOMAIN_SETUP_GUIDE.md"
echo "  - SETUP_STATUS.md"
echo "=========================================="
